project:
  type: website

website:
  title: "M. Melik Kölgesiz"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        href: blog.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



