project:
  type: website
  output-dir: _site

website:
  site-url: "https://mkolgesiz.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog-r.qmd
        text: Blog-r
      - href: "https://mkolgesiz.github.io/blog-py/blog.html"
        text: Blog-py
    right:
      - icon: github
        href: https://github.com/mkolgesiz
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/mkolgesiz.bsky.social
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: 'https://www.linkedin.com/in/mkolgesiz'

format:
  html:
    theme: 
      light: flatly
    css: styles.css
    toc: true
