project:
  type: website

website:
  title: "M. Melik Kölgesiz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



