project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
